---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service-expose
  namespace: default
  labels:
    app: catalog-service
spec:
  ports:
  - name: catalog-service
    protocol: TCP
    port: 31708
    targetPort: 1111
    nodePort: 31708
  selector:
    app: catalog-service
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  ports:
  - port: 1111
    targetPort: 1111
    name: catalog-service
  clusterIP: None
  selector:
    app: catalog-service
---    
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: catalog-service
spec:
  serviceName: "catalog-service"
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - resources:
          requests:
            cpu: 100m
            memory: 192Mi 
        name: catalog-service
        image: mycluster.icp:8500/default/kbastani/catalog-service:latest
        ports:
        - containerPort: 1111
        env:
        - name: JAVA_OPTS
          value: |
            -Xmx160m
        - name: spring.profiles.active
          value: "cloud"
        - name: spring.cloud.config.uri
          value: "http://config-service.default.svc.cluster.local:8888"
        - name: server.port
          value: "1111"
  podManagementPolicy: "Parallel"